// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eieaoaeynpjdlcciewjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZWFvYWV5bnBqZGxjY2lld2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjAzMTgsImV4cCI6MjA1NjQzNjMxOH0.tu2D7z6zR3wL2CSHtam6UdCOvDrIZRFZsp_NS04O6YU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);